INSERT INTO books (title, author, description, cover_url, genre_id, average_rating, total_reviews, published_date, posted_by)
VALUES
('1984', 'George Orwell', 'Um retrato sombrio de um regime totalitário que vigia cada pensamento dos seus cidadãos.', 'https://covers.openlibrary.org/b/olid/OL24382006M-L.jpg', (SELECT id FROM genres WHERE name = 'Distopia'), 4.8, 3241, '1949-06-08', NULL),
('Pride and Prejudice', 'Jane Austen', 'A história de Elizabeth Bennet e suas irmãs em busca de amor e independência na Inglaterra do século XIX.', 'https://covers.openlibrary.org/b/olid/OL3700132M-L.jpg', (SELECT id FROM genres WHERE name = 'Romance'), 4.7, 2894, '1813-01-28', NULL),
('The Hobbit', 'J.R.R. Tolkien', 'A jornada inesperada de Bilbo Bolseiro rumo à Montanha Solitária.', 'https://covers.openlibrary.org/b/olid/OL10683695M-L.jpg', (SELECT id FROM genres WHERE name = 'Fantasia'), 4.9, 4102, '1937-09-21', NULL),
('Dom Casmurro', 'Machado de Assis', 'Bentinho narra sua obsessão pela dúvida sobre a fidelidade de Capitu.', 'https://covers.openlibrary.org/b/olid/OL1004411M-L.jpg', (SELECT id FROM genres WHERE name = 'Romance'), 4.6, 1523, '1899-01-01', NULL),
('To Kill a Mockingbird', 'Harper Lee', 'Scout Finch relembra a infância marcada pela luta do pai contra o preconceito racial no sul dos Estados Unidos.', 'https://covers.openlibrary.org/b/olid/OL2463652M-L.jpg', (SELECT id FROM genres WHERE name = 'Drama'), 4.8, 3897, '1960-07-11', NULL),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Os excessos e ilusões do sonho americano vistos pelos olhos de Nick Carraway.', 'https://covers.openlibrary.org/b/olid/OL22152141M-L.jpg', (SELECT id FROM genres WHERE name = 'Drama'), 4.4, 2765, '1925-04-10', NULL),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Harry descobre que é um bruxo e embarca em sua primeira jornada em Hogwarts.', 'https://covers.openlibrary.org/b/olid/OL26820966M-L.jpg', (SELECT id FROM genres WHERE name = 'Fantasia'), 4.9, 5231, '1997-06-26', NULL),
('O Alquimista', 'Paulo Coelho', 'O pastor Santiago parte em busca de um tesouro e descobre sua própria lenda pessoal.', 'https://covers.openlibrary.org/b/olid/OL18511145M-L.jpg', (SELECT id FROM genres WHERE name = 'Ficção'), 4.3, 3120, '1988-01-01', NULL),
('Brave New World', 'Aldous Huxley', 'Uma sociedade futurista controlada pelo prazer, pela genética e pela ausência de liberdade.', 'https://covers.openlibrary.org/b/olid/OL6504102M-L.jpg', (SELECT id FROM genres WHERE name = 'Distopia'), 4.6, 2201, '1932-01-01', NULL),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'Uma jornada pela história da humanidade, da revolução cognitiva à era da inteligência artificial.', 'https://covers.openlibrary.org/b/olid/OL27000666M-L.jpg', (SELECT id FROM genres WHERE name = 'Não-ficção'), 4.7, 4567, '2011-01-01', NULL);
